import type { Metadata } from "next";
import "../globals.css";
import { Lato } from 'next/font/google'

import "../Carosal.css"
import LayoutWrapper from "@/components/layout/LayoutWrapper";


export const metadata: Metadata = {
  title: "Allen Sportswear",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: ['400', '900'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body className={`${lato.className} segoe-ui`}>
        <LayoutWrapper>

          {children}
        </LayoutWrapper>

      </body>
    </html>
  );
}
